[profile.default]
auto_detect_solc = true

src = "src"
out = "out"
libs = ["lib"]
via_ir = true

[profile.local]
via_ir = false

remappings = [
    '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
